// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4693mPMKgMlXAi83o2JuzV524UMza8Ts',
    appId: '1:97244570522:web:b8a98111803067111d5023',
    messagingSenderId: '97244570522',
    projectId: 'catgpt-5d80f',
    authDomain: 'catgpt-5d80f.firebaseapp.com',
    storageBucket: 'catgpt-5d80f.appspot.com',
    measurementId: 'G-ZXXDNRRGFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkoYx-BqJYB5B1tl5UU4T1Q9Pb-VMAQQ',
    appId: '1:97244570522:android:1a422dd0f93a50e81d5023',
    messagingSenderId: '97244570522',
    projectId: 'catgpt-5d80f',
    storageBucket: 'catgpt-5d80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5J54EQmobXggtkS1c85ioYWKDpKA_oE',
    appId: '1:97244570522:ios:c1f7782cddea4b6b1d5023',
    messagingSenderId: '97244570522',
    projectId: 'catgpt-5d80f',
    storageBucket: 'catgpt-5d80f.appspot.com',
    iosClientId: '97244570522-i2634r0808o8fkadjfgop7goemqkmftv.apps.googleusercontent.com',
    iosBundleId: 'thanhnamitit.com.wisechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp5J54EQmobXggtkS1c85ioYWKDpKA_oE',
    appId: '1:97244570522:ios:c1f7782cddea4b6b1d5023',
    messagingSenderId: '97244570522',
    projectId: 'catgpt-5d80f',
    storageBucket: 'catgpt-5d80f.appspot.com',
    iosClientId: '97244570522-i2634r0808o8fkadjfgop7goemqkmftv.apps.googleusercontent.com',
    iosBundleId: 'thanhnamitit.com.wisechat',
  );
}
